name: Build Bootimage
on:
  push:
    branches:
      - actions-test
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build Bootimage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86

      - name: Add rust-src and tools
        run: rustup component add rust-src && rustup component add llvm-tools-preview

      - name: Build Bootimage
        run: cargo install bootimage && cargo bootimage --target x86_64-unknown-none

      - name: Run Tests
        run: cargo test

      - name: Create Release
        if: success() && (github.ref == 'refs/tags/' || github.event_name == 'push') # Only runs on successful pushes or tag events
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/x86_64-unknown-none/debug/bootimage-lauch_os.bin
          tag_name: Release
          name: Release ${{ github.ref }}
          body: Bootable image release for ${{ github.ref }}
